import os
import sys
from dotenv import load_dotenv

# Check openCV version
import cv2
print(cv2.__version__)

# Local python script imports
import hardwareInterface.cameraConfig as cameraConfig
import hardwareInterface.roborockInterface as roborockInterface
import hardwareInterface.roborockHighResInterface as roborockHighResInterface
import hardwareInterface.controlRoborock as controlRoborock

# Main script that handles the MobiPrint computer vision based printing pipeline

# For convience aruco markers are generated by this git project https://fodi.github.io/arucosheetgen/
# and printed out to be placed on the floor for reference

if __name__ == "__main__":

    performingAPICalls = True
    headlessRun = False

    # Check flags
    if len(sys.argv) > 1:
        if '-d' in sys.argv: 
            performingAPICalls = False
            print(performingAPICalls)
        # For headless runs where open cv will not open the camera
        if '-h' in sys.argv:
            headlessRun = True


    # Loads the dotenv
    load_dotenv()

    # Side length of the ArUco marker in meters 
    # Generally aruco markers that are widht/length 50 < work the best as smaller aruco markers
    # as smaller aruco markers are harder to detect 
    aruco_marker_side_length = 0.054

    # Below are variables that must be assigned upon moving the roborock between networks
    # or if a different one is used or if you are setting up this project for the first time
    # they are typically set in the .env file that you will have to create via
    # touch .env
    # each element is assigned in the env file like this: API_KEY=your-secret-api-key-here

    # Roborock API key so that git stops complaining
    api_key = str(os.getenv("API_KEY"))
    IP_ADDRESS = str(os.getenv("IP_ADDRESS"))

    if api_key == None or IP_ADDRESS == None:
        print(f"ERROR: .env file has not been properly created, or api key/ ip address has not been added to .env file")
        exit

    cameraReference = cameraConfig.configureCamera()

    # Create interfaces, these objects hold wrapper functions for handling API calls and other complicated functionality
    localRoborockInterface = roborockHighResInterface.roborockHighResInterface(IP_ADDRESS, api_key) 

    # Intiate manual control
    if performingAPICalls:
        localRoborockInterface.initiateHighResManualControl()

    print("Status of headless " + str(headlessRun))

    # Move through markers with monotonically increasing ids
    for markerID in range(0, 4):
        print("Moving to marker ID " + str(markerID))
        controlRoborock.moveToDesignatedArucoMarker(performingAPICalls, 
                                                    localRoborockInterface, 
                                                    cameraReference, 
                                                    aruco_marker_side_length, 
                                                    desiredID=markerID, 
                                                    headlessRunStatus=headlessRun,
                                                    arucoAproxDirection=1)


    # if performingAPICalls:
    #     localRoborockInterface.disableHighResManualControl()

    cameraReference.stop()
    cv2.destroyAllWindows()             

