import os
import sys
from dotenv import load_dotenv

# Check openCV version
import cv2
print(cv2.__version__)

# Local python script imports
import subModules.hardwareInterface.cameraConfig as cameraConfig
import subModules.hardwareInterface.roborockInterface as roborockInterface
import subModules.hardwareInterface.roborockHighResInterface as roborockHighResInterface
import subModules.hardwareInterface.controlRoborock as controlRoborock
import subModules.printParsers.roborockGcodeParser as roborockGcodeParser
import subModules.robotState.robotGlobalState as robotGlobalState

# Main script that handles the MobiPrint computer vision based printing pipeline

# For convience aruco markers are generated by this git project https://fodi.github.io/arucosheetgen/
# and printed out to be placed on the floor for reference

if __name__ == "__main__":

    performingAPICalls = True
    headlessRun = False

    # Check flags
    if len(sys.argv) > 1:
        if '-d' in sys.argv: 
            performingAPICalls = False
            print(performingAPICalls)
        # For headless runs where open cv will not open the camera
        if '-h' in sys.argv:
            headlessRun = True


    # Loads the dotenv
    load_dotenv()

    # Side length of the ArUco marker in meters 
    # Generally aruco markers that are widht/length 50 < work the best as smaller aruco markers
    # as smaller aruco markers are harder to detect 
    aruco_marker_side_length = 0.054

    # Below are variables that must be assigned upon moving the roborock between networks
    # or if a different one is used or if you are setting up this project for the first time
    # they are typically set in the .env file that you will have to create via
    # touch .env
    # each element is assigned in the env file like this: API_KEY=your-secret-api-key-here

    # Roborock API key so that git stops complaining
    api_key = str(os.getenv("API_KEY"))
    IP_ADDRESS = str(os.getenv("IP_ADDRESS"))

    if api_key == None or IP_ADDRESS == None:
        print(f"ERROR: .env file has not been properly created, or api key/ ip address has not been added to .env file")
        exit

    robotGlobalStateRef = robotGlobalState(IP_ADDRESS=IP_ADDRESS,
                                           API_KEY=api_key,
                                           headlessRunStatus=headlessRun,
                                           performingAPICalls=performingAPICalls,
                                           aruco_marker_side_length=aruco_marker_side_length)

    # Create interfaces, these objects hold wrapper functions for handling API calls and other complicated functionality
    localRoborockInterface = roborockHighResInterface.roborockHighResInterface(IP_ADDRESS, api_key) 

    # Intiate manual control
    robotGlobalStateRef.initiateRobotSubsystems()

    # THIS IS WHERE THE MAIN ROBOT CODE WILL BE RUN

    # if performingAPICalls:
    #     localRoborockInterface.disableHighResManualControl()

    robotGlobalStateRef.stopRobotSubsystems()
    cv2.destroyAllWindows()             

